<?php
/*
@在浏览器选择YOU2PHP缺省国家和地区
2018-7-28
*/
$gls=array(
"HK"=>"香港",
"TW"=>"台湾",
"JP"=>"日本",
"KR"=>"韩国",
"US"=>"美国",
"FR"=>"法国",
"UK"=>"英国",
"DE"=>"德国",
"IN"=>"印度",
"DZ"=>"阿尔及利亚",
"ar"=>"阿根廷",
"au"=>"澳大利亚",
"at"=>"奥地利",
"az"=>"阿塞拜疆",
"bh"=>"巴林",
"by"=>"白俄罗斯",
"be"=>"比利时",
"ba"=>"波斯尼亚和黑塞哥维那",
"br"=>"巴西",
"bg"=>"保加利亚",
"ca"=>"加拿大",
"cl"=>"智利",
"co"=>"哥伦比亚",
"hr"=>"克罗地亚",
"cz"=>"捷克共和国",
"dk"=>"丹麦",
"eg"=>"埃及",
"ee"=>"爱沙尼亚",
"FI"=>"芬兰",
"ge"=>"格鲁吉亚",
"GH"=>"加纳",
"gr"=>"希腊",
"hu"=>"匈牙利",
"is"=>"冰岛",
"id"=>"印度尼西亚",
"iq"=>"伊拉克",
"ie"=>"爱尔兰",
"il"=>"以色列",
"it"=>"意大利",
"jm"=>"牙买加",
"jo"=>"约旦",
"kz"=>"哈萨克斯坦",
"ke"=>"肯尼亚",
"kw"=>"科威特",
"lv"=>"拉脱维亚",
"lb"=>"黎巴嫩",
"ly"=>"利比亚",
"lt"=>"立陶宛",
"lu"=>"卢森堡",
"mk"=>"马其顿",
"my"=>"马来西亚",
"MX"=>"墨西哥",
"me"=>"黑山",
"ma"=>"摩洛哥",
"np"=>"尼泊尔",
"nl"=>"荷兰",
"nz"=>"新西兰",
"ng"=>"尼日利亚",
"否"=>"挪威",
"om"=>"阿曼",
"pk"=>"巴基斯坦",
"pe"=>"秘鲁",
"ph"=>"菲律宾",
"pl"=>"波兰",
"pt"=>"葡萄牙",
"pr"=>"波多黎各",
"qa"=>"卡塔尔",
"ro"=>"罗马尼亚",
"ru"=>"俄罗斯",
"sa"=>"沙特阿拉伯",
"sn"=>"塞内加尔",
"rs"=>"塞尔维亚",
"sg"=>"新加坡",
"sk"=>"斯洛伐克",
"si"=>"斯洛文尼亚",
"za"=>"南非",
"es"=>"西班牙",
"LK"=>"斯里兰卡",
"SE"=>"瑞典",
"ch"=>"瑞士",
"TZ"=>"坦桑尼亚",
"th"=>"泰国",
"tn"=>"突尼斯",
"tr"=>"土耳其",
"ug"=>"乌干达",
"ua"=>"乌克兰",
"ae"=>"阿拉伯联合酋长国",
"VN"=>"越南",
"ye"=>"也门",
"ZW"=>"津巴布韦");
//可以增加更多的选项

$gl=(isset($_COOKIE['gl']) && $_COOKIE['gl'])?$_COOKIE['gl']:'HK';
if(!isset($gls[$gl])){$gl='HK';}

$select[]="<select id='select_gl'>";
foreach($gls as $k=>$v){
	$is_selected=($k==$gl)?' selected ':'';
	$select[]="  <option value =\"$k\"{$is_selected}>$v</option>";
}
$select[]="</select>";
echo join("\n",$select);
?>

<script>
$(document).ready(function() {
	$("#select_gl").change(function(){
		var gl=$(this).children('option:selected').val()
		document.cookie="gl="+gl;
		window.location.reload()
	})
})
</script>
